name: notes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.1
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.0
  firebase_auth: ^3.5.1
  firebase_core: ^1.20.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  path: ^1.8.1
  path_provider: ^2.0.11
  share_plus: ^4.0.10+1
  sqflite: ^2.0.3+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
